# Dependabot 配置文件
# 此文件用于配置 GitHub Dependabot 自动更新依赖

version: 2
updates:
  # 维护 pip 依赖
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    # 指定自动标记安全问题
    labels:
      - "dependencies"
      - "security"
    # 忽略某些更新
    ignore:
      # 忽略某些依赖的特定版本更新
      # - dependency-name: "package-name"
      #   versions: ["1.x", "2.x"]
    # 版本控制策略
    versioning-strategy: auto
    # 允许自动合并非主要版本更新
    allow:
      - dependency-type: "all"
      - dependency-name: "*"
        update-type: "semver-minor"
        update-type: "semver-patch"
    commit-message:
      prefix: "依赖"
      include: "scope"
