name: Build and Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build wheel package
        run: |
          python setup.py bdist_wheel
          echo "Wheel package created successfully"

      - name: Check for dependency updates
        run: |
          chmod +x ./update_dependencies.sh
          ./update_dependencies.sh

      - name: Get version info
        id: version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d)
          VERSION="${DATE}-${COMMIT_HASH}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "版本信息: ${VERSION}"

      - name: Upload wheel package
        uses: actions/upload-artifact@v4
        with:
          name: aur-update-checker-python-${{ env.VERSION }}
          path: dist/*.whl
          if-no-files-found: error
          compression-level: 6
          overwrite: false
