name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka
          pip show nuitka

      - name: Run build script
        run: |
          # 使用 package.py 进行打包
          if ! python package.py; then
            echo "Nuitka 打包失败，尝试使用 pyinstaller 作为备用方案"
            pip install pyinstaller
            pyinstaller --onefile --name aur-update-checker-python main.py
          fi

      - name: Check for dependency updates
        run: |
          chmod +x ./update_dependencies.sh
          ./update_dependencies.sh

      - name: Get version info
        id: version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d)
          VERSION="${DATE}-${COMMIT_HASH}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "版本信息: ${VERSION}"

      - name: Package dist files
        run: |
          cd dist
          tar -czvf "../aur-update-checker-python-${VERSION}.tar.gz" .
          cd ..
          echo "打包完成：aur-update-checker-python-${VERSION}.tar.gz"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./aur-update-checker-python-${{ env.VERSION }}.tar.gz
          asset_name: aur-update-checker-python-${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
